[package]
name    = "terve"
version = "0.1.0"
authors = ["Jukka Palomäki <jukka@jpalomaki.fi>"]
edition = "2018"

[dependencies]
regex       = "~1.5"
pico-args   = "~0.4"
reqwest     = { version = "~0.11", default-features = false, features = ["rustls-tls", "json", "blocking"] }
zip         = "~0.5"
tempfile    = "~3.2"
dirs        = "~3.0"
serde       = { version = "~1.0", features = ["derive"] }
semver      = "~1.0"
sha2        = "~0.9"
hex         = "~0.4"
pgp         = "~0.7"
bytes       = "~1.0"

[dev-dependencies]
assert_cmd  = "~1.0"
predicates  = "~1.0"

[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
