[package]
name    = "terve"
version = "0.1.0"
authors = ["Jukka Palomäki <jukka@jpalomaki.fi>"]
edition = "2018"

[dependencies]
regex       = "~1.5"
argh        = "~0.1"
reqwest     = { version = "~0.11", default-features = false, features = ["rustls-tls", "json", "blocking"] }
zip         = "~0.5"
tempfile    = "~3.2"
home        = "~0.5"
serde       = { version = "~1.0", features = ["derive"] }
semver      = "~0.11"
sha2        = "~0.9"
hex         = "~0.4"

[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
