name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Check for errors
        run: cargo check

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run clippy lints
        run: cargo clippy -- -D warnings

  build:
    needs: check
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-18.04
          - target: x86_64-apple-darwin
            runner: macos-10.15
          - target: x86_64-pc-windows-msvc
            runner: windows-2016
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Run debug build
        run: cargo build --target ${{ matrix.target }}

      - name: Run all tests
        run: cargo test --target ${{ matrix.target }}
